/**
 * ============================================
 * GUILD MASTER - Complete Bestiary (Design Doc v2)
 * ============================================
 * 252 Enemy Templates across 10 Families
 *
 * DESIGN PRINCIPLE:
 * Enemies have NO inherent tier. They are stat distribution templates.
 * The zone/quest determines what tier multiplier to apply at spawn time.
 *
 * Stat Distribution: ATK + DEF + SPD + WILL = 1.0
 * ============================================
 */

/**
 * Enemy family types
 * @readonly
 * @enum {string}
 */
const EnemyFamily = {
    VERMIN: 'Vermin',
    BEASTS: 'Beasts',
    GOBLINOID: 'Goblinoid',
    UNDEAD: 'Undead',
    HUMANOID: 'Humanoid',
    ORC_BRUTE: 'Orc/Brute',
    ARCANE: 'Arcane',
    DEMON: 'Demon',
    DRACONIC: 'Draconic',
    ABOMINATION: 'Abomination',
};

/**
 * Hunger access levels - determines what hunger items can drop
 * @readonly
 * @enum {string}
 */
const HungerAccess = {
    NO_REPLETE: 'No Replete',    // Cannot drop Replete items
    STANDARD: 'Standard',         // Standard hunger range only
    FULL_ACCESS: 'Full Access',   // Can drop any hunger including legendary
};

/**
 * Enemy archetype descriptions
 * @readonly
 * @enum {string}
 */
const Archetype = {
    BRUISER: 'Bruiser',           // ATK + DEF - Tanky damage dealer
    ASSASSIN: 'Assassin',         // ATK + SPD - Fast, kills before being killed
    GLASS_CANNON: 'Glass Cannon', // Pure ATK - Max damage, paper thin
    MAGE: 'Mage',                 // WILL-heavy - Magic nukes, fragile
    SUMMONER: 'Summoner',         // Deep WILL - Army builder
    PALADIN: 'Paladin',           // DEF + WILL - Survives everything, hybrid damage
    TANK: 'Tank',                 // Pure DEF - Unkillable, low damage
};

Object.freeze(EnemyFamily);
Object.freeze(HungerAccess);
Object.freeze(Archetype);

/**
 * ============================================
 * BESTIARY - All 252 Enemy Templates
 * ============================================
 */
const BESTIARY = {
    // ==================== VERMIN (28) ====================
    // Rats, bats, insects, spiders — fodder-heavy swarm creatures

    sewer_rat: {
        id: 'sewer_rat',
        name: 'Sewer Rat',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.30, def: 0.10, spd: 0.55, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🐀',
        skills: [],
    },
    plague_rat: {
        id: 'plague_rat',
        name: 'Plague Rat',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.25, def: 0.10, spd: 0.45, will: 0.20 },
        archetype: Archetype.ASSASSIN,
        icon: '🐀',
        skills: [],
    },
    giant_rat: {
        id: 'giant_rat',
        name: 'Giant Rat',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.40, def: 0.15, spd: 0.40, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🐀',
        skills: [],
    },
    rat_king: {
        id: 'rat_king',
        name: 'Rat King',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.30, def: 0.20, spd: 0.25, will: 0.25 },
        archetype: Archetype.SUMMONER,
        icon: '🐀',
        skills: ['summon'],
    },
    cave_bat: {
        id: 'cave_bat',
        name: 'Cave Bat',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.25, def: 0.05, spd: 0.65, will: 0.05 },
        archetype: Archetype.GLASS_CANNON,
        icon: '🦇',
        skills: [],
    },
    vampire_bat: {
        id: 'vampire_bat',
        name: 'Vampire Bat',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.10, spd: 0.45, will: 0.10 },
        archetype: Archetype.ASSASSIN,
        icon: '🦇',
        skills: ['leech'],
    },
    dire_bat: {
        id: 'dire_bat',
        name: 'Dire Bat',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.40, def: 0.15, spd: 0.40, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🦇',
        skills: [],
    },
    swarm_bat: {
        id: 'swarm_bat',
        name: 'Swarm Bat',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.45, def: 0.10, spd: 0.40, will: 0.05 },
        archetype: Archetype.GLASS_CANNON,
        icon: '🦇',
        skills: [],
    },
    blood_wing: {
        id: 'blood_wing',
        name: 'Blood Wing',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.15, spd: 0.35, will: 0.10 },
        archetype: Archetype.ASSASSIN,
        icon: '🦇',
        skills: ['leech'],
    },
    cockroach: {
        id: 'cockroach',
        name: 'Cockroach',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.15, def: 0.35, spd: 0.45, will: 0.05 },
        archetype: Archetype.TANK,
        icon: '🪳',
        skills: [],
    },
    giant_beetle: {
        id: 'giant_beetle',
        name: 'Giant Beetle',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.30, def: 0.40, spd: 0.25, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🪲',
        skills: [],
    },
    scarab: {
        id: 'scarab',
        name: 'Scarab',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.25, def: 0.35, spd: 0.30, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🪲',
        skills: [],
    },
    stag_beetle: {
        id: 'stag_beetle',
        name: 'Stag Beetle',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.35, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🪲',
        skills: ['bash'],
    },
    fire_beetle: {
        id: 'fire_beetle',
        name: 'Fire Beetle',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.30, def: 0.30, spd: 0.20, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🪲',
        skills: ['fireball'],
    },
    corpse_beetle: {
        id: 'corpse_beetle',
        name: 'Corpse Beetle',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.30, spd: 0.20, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🪲',
        skills: [],
    },
    spider_hatchling: {
        id: 'spider_hatchling',
        name: 'Spider Hatchling',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.30, def: 0.05, spd: 0.60, will: 0.05 },
        archetype: Archetype.GLASS_CANNON,
        icon: '🕷️',
        skills: [],
    },
    cave_spider: {
        id: 'cave_spider',
        name: 'Cave Spider',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.15, spd: 0.45, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🕷️',
        skills: [],
    },
    giant_spider: {
        id: 'giant_spider',
        name: 'Giant Spider',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.40, def: 0.20, spd: 0.40, will: 0.00 },
        archetype: Archetype.ASSASSIN,
        icon: '🕷️',
        skills: [],
    },
    poison_spider: {
        id: 'poison_spider',
        name: 'Poison Spider',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.30, def: 0.15, spd: 0.35, will: 0.20 },
        archetype: Archetype.ASSASSIN,
        icon: '🕷️',
        skills: [],
    },
    broodmother: {
        id: 'broodmother',
        name: 'Broodmother',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.30, def: 0.25, spd: 0.20, will: 0.25 },
        archetype: Archetype.SUMMONER,
        icon: '🕷️',
        skills: ['summon'],
    },
    widow_queen: {
        id: 'widow_queen',
        name: 'Widow Queen',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.20, spd: 0.25, will: 0.20 },
        archetype: Archetype.ASSASSIN,
        icon: '🕷️',
        skills: ['summon'],
    },
    centipede: {
        id: 'centipede',
        name: 'Centipede',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.15, spd: 0.45, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🐛',
        skills: [],
    },
    giant_centipede: {
        id: 'giant_centipede',
        name: 'Giant Centipede',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.45, def: 0.20, spd: 0.30, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐛',
        skills: [],
    },
    venomous_centipede: {
        id: 'venomous_centipede',
        name: 'Venomous Centipede',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.15, spd: 0.30, will: 0.20 },
        archetype: Archetype.ASSASSIN,
        icon: '🐛',
        skills: [],
    },
    carrion_crawler: {
        id: 'carrion_crawler',
        name: 'Carrion Crawler',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.25, spd: 0.20, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🐛',
        skills: [],
    },
    scorpion: {
        id: 'scorpion',
        name: 'Scorpion',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.40, def: 0.25, spd: 0.30, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🦂',
        skills: [],
    },
    giant_scorpion: {
        id: 'giant_scorpion',
        name: 'Giant Scorpion',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.30, spd: 0.20, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🦂',
        skills: ['bash'],
    },
    emperor_scorpion: {
        id: 'emperor_scorpion',
        name: 'Emperor Scorpion',
        family: EnemyFamily.VERMIN,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.35, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🦂',
        skills: ['bash', 'frenzy'],
    },

    // ==================== BEASTS (34) ====================
    // Wolves, bears, cats, birds, snakes — natural predators

    wolf_pup: {
        id: 'wolf_pup',
        name: 'Wolf Pup',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.10, spd: 0.50, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🐺',
        skills: [],
    },
    wolf: {
        id: 'wolf',
        name: 'Wolf',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.45, def: 0.15, spd: 0.35, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🐺',
        skills: [],
    },
    dire_wolf: {
        id: 'dire_wolf',
        name: 'Dire Wolf',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.15, spd: 0.35, will: 0.00 },
        archetype: Archetype.ASSASSIN,
        icon: '🐺',
        skills: ['frenzy'],
    },
    alpha_wolf: {
        id: 'alpha_wolf',
        name: 'Alpha Wolf',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.20, spd: 0.30, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐺',
        skills: ['frenzy'],
    },
    winter_wolf: {
        id: 'winter_wolf',
        name: 'Winter Wolf',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.20, spd: 0.25, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🐺',
        skills: [],
    },
    worg: {
        id: 'worg',
        name: 'Worg',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.25, spd: 0.25, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🐺',
        skills: ['frenzy'],
    },
    wild_boar: {
        id: 'wild_boar',
        name: 'Wild Boar',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.45, def: 0.30, spd: 0.20, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐗',
        skills: [],
    },
    dire_boar: {
        id: 'dire_boar',
        name: 'Dire Boar',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.30, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐗',
        skills: ['bash'],
    },
    razorback: {
        id: 'razorback',
        name: 'Razorback',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.55, def: 0.25, spd: 0.15, will: 0.05 },
        archetype: Archetype.GLASS_CANNON,
        icon: '🐗',
        skills: ['frenzy'],
    },
    war_boar: {
        id: 'war_boar',
        name: 'War Boar',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.35, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐗',
        skills: ['bash'],
    },
    black_bear: {
        id: 'black_bear',
        name: 'Black Bear',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.35, spd: 0.20, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐻',
        skills: [],
    },
    brown_bear: {
        id: 'brown_bear',
        name: 'Brown Bear',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.35, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐻',
        skills: ['bash'],
    },
    cave_bear: {
        id: 'cave_bear',
        name: 'Cave Bear',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.35, spd: 0.10, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐻',
        skills: ['bash', 'frenzy'],
    },
    dire_bear: {
        id: 'dire_bear',
        name: 'Dire Bear',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.35, spd: 0.10, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐻',
        skills: ['bash', 'frenzy'],
    },
    werebear: {
        id: 'werebear',
        name: 'Werebear',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.30, spd: 0.15, will: 0.15 },
        archetype: Archetype.PALADIN,
        icon: '🐻',
        skills: ['frenzy', 'second_wind'],
    },
    feral_cat: {
        id: 'feral_cat',
        name: 'Feral Cat',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.05, spd: 0.55, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🐱',
        skills: [],
    },
    mountain_lion: {
        id: 'mountain_lion',
        name: 'Mountain Lion',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.10, spd: 0.40, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🦁',
        skills: [],
    },
    panther: {
        id: 'panther',
        name: 'Panther',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.10, spd: 0.40, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🐆',
        skills: ['backstab'],
    },
    saber_tiger: {
        id: 'saber_tiger',
        name: 'Saber Tiger',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.55, def: 0.15, spd: 0.25, will: 0.05 },
        archetype: Archetype.GLASS_CANNON,
        icon: '🐅',
        skills: ['frenzy'],
    },
    dire_tiger: {
        id: 'dire_tiger',
        name: 'Dire Tiger',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.55, def: 0.20, spd: 0.20, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐅',
        skills: ['frenzy', 'cleave'],
    },
    hunting_hawk: {
        id: 'hunting_hawk',
        name: 'Hunting Hawk',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.30, def: 0.05, spd: 0.60, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🦅',
        skills: [],
    },
    giant_eagle: {
        id: 'giant_eagle',
        name: 'Giant Eagle',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.15, spd: 0.40, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🦅',
        skills: ['cleave'],
    },
    roc_fledgling: {
        id: 'roc_fledgling',
        name: 'Roc Fledgling',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.25, spd: 0.25, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🦅',
        skills: ['cleave'],
    },
    roc: {
        id: 'roc',
        name: 'Roc',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.30, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🦅',
        skills: ['cleave', 'bash'],
    },
    viper: {
        id: 'viper',
        name: 'Viper',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.30, def: 0.05, spd: 0.50, will: 0.15 },
        archetype: Archetype.ASSASSIN,
        icon: '🐍',
        skills: [],
    },
    constrictor: {
        id: 'constrictor',
        name: 'Constrictor',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.40, def: 0.25, spd: 0.30, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐍',
        skills: [],
    },
    giant_snake: {
        id: 'giant_snake',
        name: 'Giant Snake',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.25, spd: 0.25, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐍',
        skills: [],
    },
    king_cobra: {
        id: 'king_cobra',
        name: 'King Cobra',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.10, spd: 0.35, will: 0.20 },
        archetype: Archetype.ASSASSIN,
        icon: '🐍',
        skills: [],
    },
    basilisk: {
        id: 'basilisk',
        name: 'Basilisk',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.25, spd: 0.15, will: 0.30 },
        archetype: Archetype.MAGE,
        icon: '🐍',
        skills: [],
    },
    world_serpent: {
        id: 'world_serpent',
        name: 'World Serpent',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.30, spd: 0.10, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🐍',
        skills: ['bash', 'frenzy'],
    },
    wild_horse: {
        id: 'wild_horse',
        name: 'Wild Horse',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.25, def: 0.20, spd: 0.50, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🐴',
        skills: [],
    },
    warhorse: {
        id: 'warhorse',
        name: 'Warhorse',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.30, spd: 0.30, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐴',
        skills: ['bash'],
    },
    nightmare: {
        id: 'nightmare',
        name: 'Nightmare',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.20, spd: 0.25, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🐴',
        skills: ['fireball'],
    },
    unicorn: {
        id: 'unicorn',
        name: 'Unicorn',
        family: EnemyFamily.BEASTS,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.20, def: 0.25, spd: 0.25, will: 0.30 },
        archetype: Archetype.PALADIN,
        icon: '🦄',
        skills: ['mana_shield'],
    },

    // ==================== GOBLINOID (24) ====================
    // Goblins, hobgoblins, bugbears, gremlins — tribal hoarders

    goblin_runt: {
        id: 'goblin_runt',
        name: 'Goblin Runt',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.30, def: 0.15, spd: 0.50, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '👺',
        skills: [],
    },
    goblin: {
        id: 'goblin',
        name: 'Goblin',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.20, spd: 0.40, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '👺',
        skills: [],
    },
    goblin_scout: {
        id: 'goblin_scout',
        name: 'Goblin Scout',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.25, def: 0.10, spd: 0.60, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '👺',
        skills: ['backstab'],
    },
    goblin_warrior: {
        id: 'goblin_warrior',
        name: 'Goblin Warrior',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.25, spd: 0.25, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👺',
        skills: ['bash'],
    },
    goblin_archer: {
        id: 'goblin_archer',
        name: 'Goblin Archer',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.10, spd: 0.35, will: 0.05 },
        archetype: Archetype.GLASS_CANNON,
        icon: '👺',
        skills: [],
    },
    goblin_brute: {
        id: 'goblin_brute',
        name: 'Goblin Brute',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.30, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash'],
    },
    goblin_shaman: {
        id: 'goblin_shaman',
        name: 'Goblin Shaman',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.15, def: 0.15, spd: 0.25, will: 0.45 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['fireball', 'spark'],
    },
    goblin_pyro: {
        id: 'goblin_pyro',
        name: 'Goblin Pyro',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.25, def: 0.10, spd: 0.30, will: 0.35 },
        archetype: Archetype.MAGE,
        icon: '🔥',
        skills: ['fireball'],
    },
    goblin_assassin: {
        id: 'goblin_assassin',
        name: 'Goblin Assassin',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.10, spd: 0.35, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🗡️',
        skills: ['backstab'],
    },
    goblin_chief: {
        id: 'goblin_chief',
        name: 'Goblin Chief',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.25, spd: 0.25, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '👺',
        skills: ['bash', 'frenzy'],
    },
    goblin_king: {
        id: 'goblin_king',
        name: 'Goblin King',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.30, spd: 0.20, will: 0.20 },
        archetype: Archetype.PALADIN,
        icon: '👑',
        skills: ['bash', 'frenzy', 'second_wind'],
    },
    hobgoblin: {
        id: 'hobgoblin',
        name: 'Hobgoblin',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.35, spd: 0.20, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: [],
    },
    hobgoblin_soldier: {
        id: 'hobgoblin_soldier',
        name: 'Hobgoblin Soldier',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.35, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash'],
    },
    hobgoblin_captain: {
        id: 'hobgoblin_captain',
        name: 'Hobgoblin Captain',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.35, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave'],
    },
    hobgoblin_warlord: {
        id: 'hobgoblin_warlord',
        name: 'Hobgoblin Warlord',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.35, spd: 0.10, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave', 'frenzy'],
    },
    hobgoblin_devastator: {
        id: 'hobgoblin_devastator',
        name: 'Hobgoblin Devastator',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.45, spd: 0.10, will: 0.05 },
        archetype: Archetype.TANK,
        icon: '👹',
        skills: ['bash', 'block'],
    },
    bugbear: {
        id: 'bugbear',
        name: 'Bugbear',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.20, spd: 0.25, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐻',
        skills: ['bash'],
    },
    bugbear_stalker: {
        id: 'bugbear_stalker',
        name: 'Bugbear Stalker',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.15, spd: 0.30, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🐻',
        skills: ['backstab'],
    },
    bugbear_berserker: {
        id: 'bugbear_berserker',
        name: 'Bugbear Berserker',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.60, def: 0.15, spd: 0.20, will: 0.05 },
        archetype: Archetype.GLASS_CANNON,
        icon: '🐻',
        skills: ['frenzy', 'cleave'],
    },
    bugbear_chief: {
        id: 'bugbear_chief',
        name: 'Bugbear Chief',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.25, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🐻',
        skills: ['bash', 'frenzy'],
    },
    gremlin: {
        id: 'gremlin',
        name: 'Gremlin',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.25, def: 0.10, spd: 0.55, will: 0.10 },
        archetype: Archetype.ASSASSIN,
        icon: '👿',
        skills: [],
    },
    gremlin_tinkerer: {
        id: 'gremlin_tinkerer',
        name: 'Gremlin Tinkerer',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.20, def: 0.15, spd: 0.40, will: 0.25 },
        archetype: Archetype.MAGE,
        icon: '👿',
        skills: ['spark'],
    },
    gremlin_bomber: {
        id: 'gremlin_bomber',
        name: 'Gremlin Bomber',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.10, spd: 0.35, will: 0.25 },
        archetype: Archetype.GLASS_CANNON,
        icon: '💣',
        skills: ['fireball'],
    },
    nilbog: {
        id: 'nilbog',
        name: 'Nilbog',
        family: EnemyFamily.GOBLINOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.15, def: 0.20, spd: 0.25, will: 0.40 },
        archetype: Archetype.MAGE,
        icon: '🎭',
        skills: ['mana_shield'],
    },

    // ==================== UNDEAD (36) ====================
    // Zombies, skeletons, ghosts, vampires, liches — the risen dead

    shambling_corpse: {
        id: 'shambling_corpse',
        name: 'Shambling Corpse',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.40, spd: 0.05, will: 0.20 },
        archetype: Archetype.TANK,
        icon: '🧟',
        skills: [],
    },
    zombie: {
        id: 'zombie',
        name: 'Zombie',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.40, def: 0.40, spd: 0.05, will: 0.15 },
        archetype: Archetype.TANK,
        icon: '🧟',
        skills: [],
    },
    bloated_zombie: {
        id: 'bloated_zombie',
        name: 'Bloated Zombie',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.35, spd: 0.05, will: 0.25 },
        archetype: Archetype.TANK,
        icon: '🧟',
        skills: [],
    },
    plague_zombie: {
        id: 'plague_zombie',
        name: 'Plague Zombie',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.35, spd: 0.05, will: 0.25 },
        archetype: Archetype.TANK,
        icon: '🧟',
        skills: [],
    },
    zombie_hulk: {
        id: 'zombie_hulk',
        name: 'Zombie Hulk',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.40, spd: 0.05, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🧟',
        skills: ['bash'],
    },
    zombie_lord: {
        id: 'zombie_lord',
        name: 'Zombie Lord',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.30, spd: 0.10, will: 0.30 },
        archetype: Archetype.SUMMONER,
        icon: '🧟',
        skills: ['summon'],
    },
    skeleton: {
        id: 'skeleton',
        name: 'Skeleton',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.40, def: 0.25, spd: 0.30, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '💀',
        skills: [],
    },
    skeleton_warrior: {
        id: 'skeleton_warrior',
        name: 'Skeleton Warrior',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.30, spd: 0.20, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '💀',
        skills: ['bash'],
    },
    skeleton_archer: {
        id: 'skeleton_archer',
        name: 'Skeleton Archer',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.15, spd: 0.30, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '💀',
        skills: [],
    },
    skeleton_knight: {
        id: 'skeleton_knight',
        name: 'Skeleton Knight',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.40, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '💀',
        skills: ['bash', 'block'],
    },
    skeleton_mage: {
        id: 'skeleton_mage',
        name: 'Skeleton Mage',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.15, def: 0.15, spd: 0.25, will: 0.45 },
        archetype: Archetype.MAGE,
        icon: '💀',
        skills: ['fireball', 'spark'],
    },
    bone_giant: {
        id: 'bone_giant',
        name: 'Bone Giant',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.35, spd: 0.10, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '💀',
        skills: ['bash', 'cleave'],
    },
    skeleton_lord: {
        id: 'skeleton_lord',
        name: 'Skeleton Lord',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.30, spd: 0.15, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '💀',
        skills: ['bash', 'summon'],
    },
    ghost: {
        id: 'ghost',
        name: 'Ghost',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.20, def: 0.10, spd: 0.35, will: 0.35 },
        archetype: Archetype.MAGE,
        icon: '👻',
        skills: [],
    },
    specter: {
        id: 'specter',
        name: 'Specter',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.25, def: 0.10, spd: 0.30, will: 0.35 },
        archetype: Archetype.MAGE,
        icon: '👻',
        skills: [],
    },
    wraith: {
        id: 'wraith',
        name: 'Wraith',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.30, def: 0.10, spd: 0.25, will: 0.35 },
        archetype: Archetype.MAGE,
        icon: '👻',
        skills: ['soul_rend'],
    },
    banshee: {
        id: 'banshee',
        name: 'Banshee',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.15, def: 0.10, spd: 0.30, will: 0.45 },
        archetype: Archetype.MAGE,
        icon: '👻',
        skills: ['soul_rend'],
    },
    phantom: {
        id: 'phantom',
        name: 'Phantom',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.20, def: 0.15, spd: 0.25, will: 0.40 },
        archetype: Archetype.MAGE,
        icon: '👻',
        skills: ['mana_shield'],
    },
    ghoul: {
        id: 'ghoul',
        name: 'Ghoul',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.45, def: 0.20, spd: 0.25, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🧟',
        skills: ['leech'],
    },
    crypt_ghoul: {
        id: 'crypt_ghoul',
        name: 'Crypt Ghoul',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.20, spd: 0.20, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🧟',
        skills: ['leech'],
    },
    ghast: {
        id: 'ghast',
        name: 'Ghast',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.20, spd: 0.15, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🧟',
        skills: ['leech'],
    },
    wight: {
        id: 'wight',
        name: 'Wight',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.25, spd: 0.15, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🧟',
        skills: ['leech', 'soul_rend'],
    },
    barrow_wight: {
        id: 'barrow_wight',
        name: 'Barrow Wight',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.30, spd: 0.10, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🧟',
        skills: ['leech', 'soul_rend'],
    },
    revenant: {
        id: 'revenant',
        name: 'Revenant',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.25, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🧟',
        skills: ['frenzy', 'second_wind'],
    },
    mummy: {
        id: 'mummy',
        name: 'Mummy',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.35, spd: 0.05, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🧟',
        skills: [],
    },
    mummy_guardian: {
        id: 'mummy_guardian',
        name: 'Mummy Guardian',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.40, spd: 0.05, will: 0.20 },
        archetype: Archetype.TANK,
        icon: '🧟',
        skills: ['block'],
    },
    mummy_lord: {
        id: 'mummy_lord',
        name: 'Mummy Lord',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.25, def: 0.30, spd: 0.10, will: 0.35 },
        archetype: Archetype.PALADIN,
        icon: '🧟',
        skills: ['soul_rend', 'mana_shield'],
    },
    vampire_spawn: {
        id: 'vampire_spawn',
        name: 'Vampire Spawn',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.20, spd: 0.25, will: 0.15 },
        archetype: Archetype.ASSASSIN,
        icon: '🧛',
        skills: ['leech'],
    },
    vampire: {
        id: 'vampire',
        name: 'Vampire',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.20, spd: 0.20, will: 0.25 },
        archetype: Archetype.ASSASSIN,
        icon: '🧛',
        skills: ['leech', 'soul_rend'],
    },
    vampire_lord: {
        id: 'vampire_lord',
        name: 'Vampire Lord',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.25, spd: 0.15, will: 0.30 },
        archetype: Archetype.PALADIN,
        icon: '🧛',
        skills: ['leech', 'soul_rend', 'mana_shield'],
    },
    nosferatu: {
        id: 'nosferatu',
        name: 'Nosferatu',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.25, spd: 0.15, will: 0.25 },
        archetype: Archetype.BRUISER,
        icon: '🧛',
        skills: ['leech', 'frenzy'],
    },
    lich_apprentice: {
        id: 'lich_apprentice',
        name: 'Lich Apprentice',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.10, def: 0.15, spd: 0.20, will: 0.55 },
        archetype: Archetype.MAGE,
        icon: '☠️',
        skills: ['fireball', 'soul_rend'],
    },
    lich: {
        id: 'lich',
        name: 'Lich',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.10, def: 0.20, spd: 0.15, will: 0.55 },
        archetype: Archetype.MAGE,
        icon: '☠️',
        skills: ['fireball', 'soul_rend', 'mana_shield'],
    },
    archlich: {
        id: 'archlich',
        name: 'Archlich',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.10, def: 0.25, spd: 0.10, will: 0.55 },
        archetype: Archetype.MAGE,
        icon: '☠️',
        skills: ['meteor', 'soul_rend', 'mana_shield'],
    },
    death_knight: {
        id: 'death_knight',
        name: 'Death Knight',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.30, spd: 0.10, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '⚔️',
        skills: ['bash', 'cleave', 'soul_rend'],
    },
    demilich: {
        id: 'demilich',
        name: 'Demilich',
        family: EnemyFamily.UNDEAD,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.05, def: 0.15, spd: 0.20, will: 0.60 },
        archetype: Archetype.MAGE,
        icon: '💀',
        skills: ['meteor', 'soul_rend', 'mana_shield'],
    },

    // ==================== HUMANOID (35) ====================
    // Bandits, pirates, cultists, assassins — mortal enemies

    thug: {
        id: 'thug',
        name: 'Thug',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.25, spd: 0.30, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🥷',
        skills: [],
    },
    bandit: {
        id: 'bandit',
        name: 'Bandit',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.20, spd: 0.30, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🥷',
        skills: [],
    },
    bandit_archer: {
        id: 'bandit_archer',
        name: 'Bandit Archer',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.15, spd: 0.30, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🏹',
        skills: [],
    },
    bandit_brute: {
        id: 'bandit_brute',
        name: 'Bandit Brute',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.30, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🥷',
        skills: ['bash'],
    },
    bandit_captain: {
        id: 'bandit_captain',
        name: 'Bandit Captain',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.25, spd: 0.25, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🦹',
        skills: ['cleave'],
    },
    bandit_lord: {
        id: 'bandit_lord',
        name: 'Bandit Lord',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.30, spd: 0.20, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🦹',
        skills: ['cleave', 'frenzy'],
    },
    bandit_king: {
        id: 'bandit_king',
        name: 'Bandit King',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.30, spd: 0.15, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '👑',
        skills: ['cleave', 'frenzy', 'second_wind'],
    },
    pirate_deckhand: {
        id: 'pirate_deckhand',
        name: 'Pirate Deckhand',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.20, spd: 0.35, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🏴‍☠️',
        skills: [],
    },
    pirate: {
        id: 'pirate',
        name: 'Pirate',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.20, spd: 0.30, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🏴‍☠️',
        skills: [],
    },
    pirate_gunner: {
        id: 'pirate_gunner',
        name: 'Pirate Gunner',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.55, def: 0.15, spd: 0.25, will: 0.05 },
        archetype: Archetype.GLASS_CANNON,
        icon: '🏴‍☠️',
        skills: [],
    },
    pirate_first_mate: {
        id: 'pirate_first_mate',
        name: 'Pirate First Mate',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.25, spd: 0.25, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🏴‍☠️',
        skills: ['cleave'],
    },
    pirate_captain: {
        id: 'pirate_captain',
        name: 'Pirate Captain',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.25, spd: 0.20, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🏴‍☠️',
        skills: ['cleave', 'frenzy'],
    },
    dread_pirate: {
        id: 'dread_pirate',
        name: 'Dread Pirate',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.25, spd: 0.20, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🏴‍☠️',
        skills: ['cleave', 'frenzy', 'second_wind'],
    },
    cultist_initiate: {
        id: 'cultist_initiate',
        name: 'Cultist Initiate',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.25, def: 0.15, spd: 0.30, will: 0.30 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: [],
    },
    cultist: {
        id: 'cultist',
        name: 'Cultist',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.30, def: 0.15, spd: 0.25, will: 0.30 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['spark'],
    },
    cultist_zealot: {
        id: 'cultist_zealot',
        name: 'Cultist Zealot',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.10, spd: 0.25, will: 0.25 },
        archetype: Archetype.GLASS_CANNON,
        icon: '🧙',
        skills: ['frenzy'],
    },
    dark_acolyte: {
        id: 'dark_acolyte',
        name: 'Dark Acolyte',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.20, def: 0.15, spd: 0.25, will: 0.40 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['fireball'],
    },
    cult_priest: {
        id: 'cult_priest',
        name: 'Cult Priest',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.15, def: 0.20, spd: 0.20, will: 0.45 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['fireball', 'mana_shield'],
    },
    cult_fanatic: {
        id: 'cult_fanatic',
        name: 'Cult Fanatic',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.15, spd: 0.20, will: 0.35 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['frenzy', 'soul_rend'],
    },
    high_priest: {
        id: 'high_priest',
        name: 'High Priest',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.15, def: 0.20, spd: 0.15, will: 0.50 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['meteor', 'mana_shield'],
    },
    cult_leader: {
        id: 'cult_leader',
        name: 'Cult Leader',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.15, def: 0.25, spd: 0.15, will: 0.45 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['meteor', 'soul_rend', 'mana_shield'],
    },
    mercenary_recruit: {
        id: 'mercenary_recruit',
        name: 'Mercenary Recruit',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.30, spd: 0.25, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '⚔️',
        skills: [],
    },
    mercenary: {
        id: 'mercenary',
        name: 'Mercenary',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.30, spd: 0.20, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '⚔️',
        skills: ['bash'],
    },
    mercenary_veteran: {
        id: 'mercenary_veteran',
        name: 'Mercenary Veteran',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.30, spd: 0.20, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '⚔️',
        skills: ['bash', 'cleave'],
    },
    sellsword_captain: {
        id: 'sellsword_captain',
        name: 'Sellsword Captain',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.30, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '⚔️',
        skills: ['bash', 'cleave', 'frenzy'],
    },
    mercenary_commander: {
        id: 'mercenary_commander',
        name: 'Mercenary Commander',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.35, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '⚔️',
        skills: ['bash', 'cleave', 'second_wind'],
    },
    assassin_initiate: {
        id: 'assassin_initiate',
        name: 'Assassin Initiate',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.10, spd: 0.40, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🗡️',
        skills: [],
    },
    assassin: {
        id: 'assassin',
        name: 'Assassin',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.10, spd: 0.35, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🗡️',
        skills: ['backstab'],
    },
    shadow_blade: {
        id: 'shadow_blade',
        name: 'Shadow Blade',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.10, spd: 0.30, will: 0.10 },
        archetype: Archetype.ASSASSIN,
        icon: '🗡️',
        skills: ['backstab'],
    },
    master_assassin: {
        id: 'master_assassin',
        name: 'Master Assassin',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.15, spd: 0.25, will: 0.10 },
        archetype: Archetype.ASSASSIN,
        icon: '🗡️',
        skills: ['backstab', 'frenzy'],
    },
    grandmaster_assassin: {
        id: 'grandmaster_assassin',
        name: 'Grandmaster',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.20, spd: 0.20, will: 0.15 },
        archetype: Archetype.ASSASSIN,
        icon: '🗡️',
        skills: ['backstab', 'frenzy', 'second_wind'],
    },
    witch_hunter: {
        id: 'witch_hunter',
        name: 'Witch Hunter',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.25, spd: 0.20, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🔥',
        skills: [],
    },
    inquisitor: {
        id: 'inquisitor',
        name: 'Inquisitor',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.30, spd: 0.15, will: 0.20 },
        archetype: Archetype.PALADIN,
        icon: '⚖️',
        skills: ['bash', 'mana_shield'],
    },
    gladiator: {
        id: 'gladiator',
        name: 'Gladiator',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.25, spd: 0.20, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '⚔️',
        skills: ['cleave', 'frenzy'],
    },
    champion: {
        id: 'champion',
        name: 'Champion',
        family: EnemyFamily.HUMANOID,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.30, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🏆',
        skills: ['cleave', 'frenzy', 'second_wind'],
    },

    // ==================== ORC / BRUTE (28) ====================
    // Orcs, ogres, trolls, giants — savage strength

    orc_whelp: {
        id: 'orc_whelp',
        name: 'Orc Whelp',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.45, def: 0.25, spd: 0.25, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: [],
    },
    orc: {
        id: 'orc',
        name: 'Orc',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.50, def: 0.25, spd: 0.20, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: [],
    },
    orc_warrior: {
        id: 'orc_warrior',
        name: 'Orc Warrior',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.30, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash'],
    },
    orc_raider: {
        id: 'orc_raider',
        name: 'Orc Raider',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.20, spd: 0.25, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['frenzy'],
    },
    orc_berserker: {
        id: 'orc_berserker',
        name: 'Orc Berserker',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.60, def: 0.15, spd: 0.20, will: 0.05 },
        archetype: Archetype.GLASS_CANNON,
        icon: '👹',
        skills: ['frenzy', 'cleave'],
    },
    orc_shaman: {
        id: 'orc_shaman',
        name: 'Orc Shaman',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.20, def: 0.20, spd: 0.20, will: 0.40 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['fireball', 'mana_shield'],
    },
    orc_champion: {
        id: 'orc_champion',
        name: 'Orc Champion',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.30, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave'],
    },
    orc_warlord: {
        id: 'orc_warlord',
        name: 'Orc Warlord',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.30, spd: 0.10, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave', 'frenzy'],
    },
    orc_chieftain: {
        id: 'orc_chieftain',
        name: 'Orc Chieftain',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.30, spd: 0.10, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave', 'second_wind'],
    },
    orc_warchief: {
        id: 'orc_warchief',
        name: 'Orc Warchief',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.30, spd: 0.10, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave', 'frenzy', 'second_wind'],
    },
    ogre_runt: {
        id: 'ogre_runt',
        name: 'Ogre Runt',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.50, def: 0.35, spd: 0.10, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: [],
    },
    ogre: {
        id: 'ogre',
        name: 'Ogre',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.55, def: 0.30, spd: 0.10, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash'],
    },
    ogre_brute: {
        id: 'ogre_brute',
        name: 'Ogre Brute',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.55, def: 0.35, spd: 0.05, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave'],
    },
    two_headed_ogre: {
        id: 'two_headed_ogre',
        name: 'Two-Headed Ogre',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.55, def: 0.30, spd: 0.05, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave'],
    },
    ogre_mage: {
        id: 'ogre_mage',
        name: 'Ogre Mage',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.25, spd: 0.10, will: 0.35 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['fireball', 'mana_shield'],
    },
    ogre_lord: {
        id: 'ogre_lord',
        name: 'Ogre Lord',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.35, spd: 0.05, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave', 'frenzy'],
    },
    troll_whelp: {
        id: 'troll_whelp',
        name: 'Troll Whelp',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.35, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['second_wind'],
    },
    troll: {
        id: 'troll',
        name: 'Troll',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.35, spd: 0.10, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'second_wind'],
    },
    cave_troll: {
        id: 'cave_troll',
        name: 'Cave Troll',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.40, spd: 0.05, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'second_wind'],
    },
    war_troll: {
        id: 'war_troll',
        name: 'War Troll',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.40, spd: 0.05, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave', 'second_wind'],
    },
    dire_troll: {
        id: 'dire_troll',
        name: 'Dire Troll',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.55, def: 0.35, spd: 0.05, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave', 'frenzy', 'second_wind'],
    },
    troll_king: {
        id: 'troll_king',
        name: 'Troll King',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.40, spd: 0.05, will: 0.05 },
        archetype: Archetype.TANK,
        icon: '👑',
        skills: ['bash', 'cleave', 'second_wind', 'block'],
    },
    hill_giant: {
        id: 'hill_giant',
        name: 'Hill Giant',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.35, spd: 0.10, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🗿',
        skills: ['bash', 'cleave'],
    },
    stone_giant: {
        id: 'stone_giant',
        name: 'Stone Giant',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.50, spd: 0.05, will: 0.05 },
        archetype: Archetype.TANK,
        icon: '🗿',
        skills: ['bash', 'block'],
    },
    frost_giant: {
        id: 'frost_giant',
        name: 'Frost Giant',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.30, spd: 0.10, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '❄️',
        skills: ['bash', 'cleave'],
    },
    fire_giant: {
        id: 'fire_giant',
        name: 'Fire Giant',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.30, spd: 0.05, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🔥',
        skills: ['bash', 'cleave', 'fireball'],
    },
    storm_giant: {
        id: 'storm_giant',
        name: 'Storm Giant',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.25, spd: 0.15, will: 0.25 },
        archetype: Archetype.PALADIN,
        icon: '⛈️',
        skills: ['bash', 'spark', 'mana_shield'],
    },
    titan: {
        id: 'titan',
        name: 'Titan',
        family: EnemyFamily.ORC_BRUTE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.30, spd: 0.10, will: 0.25 },
        archetype: Archetype.PALADIN,
        icon: '🗿',
        skills: ['bash', 'cleave', 'meteor', 'mana_shield'],
    },

    // ==================== ARCANE (29) ====================
    // Mages, elementals, golems, constructs — magical creatures

    apprentice_mage: {
        id: 'apprentice_mage',
        name: 'Apprentice Mage',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.15, def: 0.15, spd: 0.30, will: 0.40 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['spark'],
    },
    hedge_wizard: {
        id: 'hedge_wizard',
        name: 'Hedge Wizard',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.15, def: 0.15, spd: 0.25, will: 0.45 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['fireball'],
    },
    battle_mage: {
        id: 'battle_mage',
        name: 'Battle Mage',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.25, def: 0.20, spd: 0.20, will: 0.35 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['fireball', 'spark'],
    },
    archmage: {
        id: 'archmage',
        name: 'Archmage',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.10, def: 0.20, spd: 0.15, will: 0.55 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['meteor', 'mana_shield'],
    },
    warlock: {
        id: 'warlock',
        name: 'Warlock',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.15, def: 0.15, spd: 0.20, will: 0.50 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['soul_rend', 'fireball'],
    },
    fire_elemental: {
        id: 'fire_elemental',
        name: 'Fire Elemental',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.10, spd: 0.25, will: 0.20 },
        archetype: Archetype.GLASS_CANNON,
        icon: '🔥',
        skills: ['fireball'],
    },
    water_elemental: {
        id: 'water_elemental',
        name: 'Water Elemental',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.25, def: 0.35, spd: 0.20, will: 0.20 },
        archetype: Archetype.TANK,
        icon: '💧',
        skills: [],
    },
    earth_elemental: {
        id: 'earth_elemental',
        name: 'Earth Elemental',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.45, spd: 0.05, will: 0.15 },
        archetype: Archetype.TANK,
        icon: '🪨',
        skills: ['bash'],
    },
    air_elemental: {
        id: 'air_elemental',
        name: 'Air Elemental',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.30, def: 0.10, spd: 0.45, will: 0.15 },
        archetype: Archetype.ASSASSIN,
        icon: '💨',
        skills: ['spark'],
    },
    lightning_elemental: {
        id: 'lightning_elemental',
        name: 'Lightning Elemental',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.10, spd: 0.30, will: 0.20 },
        archetype: Archetype.GLASS_CANNON,
        icon: '⚡',
        skills: ['spark'],
    },
    ice_elemental: {
        id: 'ice_elemental',
        name: 'Ice Elemental',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.35, spd: 0.15, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '❄️',
        skills: [],
    },
    elemental_lord: {
        id: 'elemental_lord',
        name: 'Elemental Lord',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.25, spd: 0.15, will: 0.30 },
        archetype: Archetype.PALADIN,
        icon: '🌪️',
        skills: ['fireball', 'spark', 'mana_shield'],
    },
    clay_golem: {
        id: 'clay_golem',
        name: 'Clay Golem',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.45, spd: 0.05, will: 0.15 },
        archetype: Archetype.TANK,
        icon: '🗿',
        skills: ['bash'],
    },
    stone_golem: {
        id: 'stone_golem',
        name: 'Stone Golem',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.50, spd: 0.05, will: 0.10 },
        archetype: Archetype.TANK,
        icon: '🗿',
        skills: ['bash', 'block'],
    },
    iron_golem: {
        id: 'iron_golem',
        name: 'Iron Golem',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.50, spd: 0.05, will: 0.05 },
        archetype: Archetype.TANK,
        icon: '🤖',
        skills: ['bash', 'block'],
    },
    flesh_golem: {
        id: 'flesh_golem',
        name: 'Flesh Golem',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.35, spd: 0.10, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🧟',
        skills: ['bash', 'frenzy'],
    },
    obsidian_golem: {
        id: 'obsidian_golem',
        name: 'Obsidian Golem',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.45, spd: 0.05, will: 0.10 },
        archetype: Archetype.TANK,
        icon: '🗿',
        skills: ['bash', 'block', 'thorns'],
    },
    mithril_golem: {
        id: 'mithril_golem',
        name: 'Mithril Golem',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.40, spd: 0.10, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🤖',
        skills: ['bash', 'cleave', 'block'],
    },
    arcane_construct: {
        id: 'arcane_construct',
        name: 'Arcane Construct',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.30, spd: 0.15, will: 0.25 },
        archetype: Archetype.PALADIN,
        icon: '🤖',
        skills: ['fireball', 'mana_shield'],
    },
    animated_armor: {
        id: 'animated_armor',
        name: 'Animated Armor',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.45, spd: 0.10, will: 0.05 },
        archetype: Archetype.TANK,
        icon: '🛡️',
        skills: ['bash', 'block'],
    },
    flying_sword: {
        id: 'flying_sword',
        name: 'Flying Sword',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.10, spd: 0.35, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '⚔️',
        skills: [],
    },
    shield_guardian: {
        id: 'shield_guardian',
        name: 'Shield Guardian',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.55, spd: 0.05, will: 0.10 },
        archetype: Archetype.TANK,
        icon: '🛡️',
        skills: ['bash', 'block'],
    },
    homunculus: {
        id: 'homunculus',
        name: 'Homunculus',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.25, def: 0.15, spd: 0.40, will: 0.20 },
        archetype: Archetype.ASSASSIN,
        icon: '👤',
        skills: [],
    },
    familiar: {
        id: 'familiar',
        name: 'Familiar',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.20, def: 0.10, spd: 0.45, will: 0.25 },
        archetype: Archetype.MAGE,
        icon: '🐱',
        skills: ['spark'],
    },
    will_o_wisp: {
        id: 'will_o_wisp',
        name: "Will-o'-Wisp",
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.25, def: 0.05, spd: 0.40, will: 0.30 },
        archetype: Archetype.MAGE,
        icon: '✨',
        skills: ['spark'],
    },
    living_spell: {
        id: 'living_spell',
        name: 'Living Spell',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.10, def: 0.10, spd: 0.25, will: 0.55 },
        archetype: Archetype.MAGE,
        icon: '✨',
        skills: ['meteor'],
    },
    mana_wyrm: {
        id: 'mana_wyrm',
        name: 'Mana Wyrm',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.20, def: 0.15, spd: 0.35, will: 0.30 },
        archetype: Archetype.MAGE,
        icon: '🐉',
        skills: ['spark'],
    },
    arcane_horror: {
        id: 'arcane_horror',
        name: 'Arcane Horror',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.15, def: 0.15, spd: 0.20, will: 0.50 },
        archetype: Archetype.MAGE,
        icon: '👁️',
        skills: ['meteor', 'soul_rend', 'mana_shield'],
    },
    spell_weaver: {
        id: 'spell_weaver',
        name: 'Spell Weaver',
        family: EnemyFamily.ARCANE,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.10, def: 0.20, spd: 0.20, will: 0.50 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['meteor', 'mana_shield'],
    },

    // ==================== DEMON (27) ====================
    // Imps, fiends, devils, demon lords — denizens of the abyss

    imp: {
        id: 'imp',
        name: 'Imp',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.30, def: 0.10, spd: 0.40, will: 0.20 },
        archetype: Archetype.ASSASSIN,
        icon: '👿',
        skills: ['fireball'],
    },
    quasit: {
        id: 'quasit',
        name: 'Quasit',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.10, spd: 0.45, will: 0.10 },
        archetype: Archetype.ASSASSIN,
        icon: '👿',
        skills: [],
    },
    dretch: {
        id: 'dretch',
        name: 'Dretch',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.40, def: 0.30, spd: 0.15, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: [],
    },
    manes: {
        id: 'manes',
        name: 'Manes',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.35, spd: 0.15, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: [],
    },
    hell_hound: {
        id: 'hell_hound',
        name: 'Hell Hound',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.15, spd: 0.30, will: 0.10 },
        archetype: Archetype.ASSASSIN,
        icon: '🐕',
        skills: ['fireball'],
    },
    shadow_demon: {
        id: 'shadow_demon',
        name: 'Shadow Demon',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.15, spd: 0.30, will: 0.15 },
        archetype: Archetype.ASSASSIN,
        icon: '👤',
        skills: ['backstab'],
    },
    succubus: {
        id: 'succubus',
        name: 'Succubus',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.25, def: 0.15, spd: 0.25, will: 0.35 },
        archetype: Archetype.MAGE,
        icon: '😈',
        skills: ['leech', 'soul_rend'],
    },
    incubus: {
        id: 'incubus',
        name: 'Incubus',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.15, spd: 0.25, will: 0.25 },
        archetype: Archetype.ASSASSIN,
        icon: '😈',
        skills: ['leech', 'backstab'],
    },
    vrock: {
        id: 'vrock',
        name: 'Vrock',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.20, spd: 0.20, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🦅',
        skills: ['cleave'],
    },
    hezrou: {
        id: 'hezrou',
        name: 'Hezrou',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.30, spd: 0.10, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🐸',
        skills: ['bash'],
    },
    glabrezu: {
        id: 'glabrezu',
        name: 'Glabrezu',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.25, spd: 0.10, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🦂',
        skills: ['bash', 'cleave'],
    },
    nalfeshnee: {
        id: 'nalfeshnee',
        name: 'Nalfeshnee',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.25, spd: 0.10, will: 0.30 },
        archetype: Archetype.PALADIN,
        icon: '🐗',
        skills: ['bash', 'fireball'],
    },
    marilith: {
        id: 'marilith',
        name: 'Marilith',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.25, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🐍',
        skills: ['cleave', 'frenzy'],
    },
    balor: {
        id: 'balor',
        name: 'Balor',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.25, spd: 0.10, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['cleave', 'frenzy', 'fireball'],
    },
    pit_fiend: {
        id: 'pit_fiend',
        name: 'Pit Fiend',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.25, spd: 0.10, will: 0.25 },
        archetype: Archetype.PALADIN,
        icon: '👹',
        skills: ['cleave', 'fireball', 'mana_shield'],
    },
    bone_devil: {
        id: 'bone_devil',
        name: 'Bone Devil',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.25, spd: 0.20, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '💀',
        skills: ['bash'],
    },
    chain_devil: {
        id: 'chain_devil',
        name: 'Chain Devil',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.30, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '⛓️',
        skills: ['bash'],
    },
    ice_devil: {
        id: 'ice_devil',
        name: 'Ice Devil',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.30, spd: 0.15, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '❄️',
        skills: ['bash', 'cleave'],
    },
    horned_devil: {
        id: 'horned_devil',
        name: 'Horned Devil',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.25, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave', 'frenzy'],
    },
    erinyes: {
        id: 'erinyes',
        name: 'Erinyes',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.20, spd: 0.20, will: 0.15 },
        archetype: Archetype.ASSASSIN,
        icon: '👼',
        skills: ['backstab', 'fireball'],
    },
    lemure: {
        id: 'lemure',
        name: 'Lemure',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.30, def: 0.40, spd: 0.10, will: 0.20 },
        archetype: Archetype.TANK,
        icon: '👹',
        skills: [],
    },
    spined_devil: {
        id: 'spined_devil',
        name: 'Spined Devil',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.20, spd: 0.25, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '👿',
        skills: ['thorns'],
    },
    bearded_devil: {
        id: 'bearded_devil',
        name: 'Bearded Devil',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.25, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'frenzy'],
    },
    demon_prince: {
        id: 'demon_prince',
        name: 'Demon Prince',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.25, spd: 0.10, will: 0.25 },
        archetype: Archetype.PALADIN,
        icon: '👑',
        skills: ['cleave', 'frenzy', 'meteor', 'mana_shield'],
    },
    demon_lord: {
        id: 'demon_lord',
        name: 'Demon Lord',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.25, spd: 0.10, will: 0.30 },
        archetype: Archetype.PALADIN,
        icon: '👑',
        skills: ['cleave', 'soul_rend', 'meteor', 'mana_shield'],
    },
    archdevil: {
        id: 'archdevil',
        name: 'Archdevil',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.30, spd: 0.10, will: 0.30 },
        archetype: Archetype.PALADIN,
        icon: '👑',
        skills: ['cleave', 'soul_rend', 'meteor', 'mana_shield', 'second_wind'],
    },
    abyssal_lord: {
        id: 'abyssal_lord',
        name: 'Abyssal Lord',
        family: EnemyFamily.DEMON,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.30, spd: 0.10, will: 0.25 },
        archetype: Archetype.PALADIN,
        icon: '👑',
        skills: ['cleave', 'frenzy', 'meteor', 'mana_shield', 'second_wind'],
    },

    // ==================== DRACONIC (24) ====================
    // Kobolds, drakes, wyverns, dragons — scaled terror

    kobold: {
        id: 'kobold',
        name: 'Kobold',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.30, def: 0.20, spd: 0.45, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🦎',
        skills: [],
    },
    kobold_warrior: {
        id: 'kobold_warrior',
        name: 'Kobold Warrior',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.25, spd: 0.30, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🦎',
        skills: [],
    },
    kobold_trapper: {
        id: 'kobold_trapper',
        name: 'Kobold Trapper',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.15, spd: 0.45, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🦎',
        skills: ['backstab'],
    },
    kobold_shaman: {
        id: 'kobold_shaman',
        name: 'Kobold Shaman',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.15, def: 0.15, spd: 0.30, will: 0.40 },
        archetype: Archetype.MAGE,
        icon: '🧙',
        skills: ['fireball'],
    },
    kobold_king: {
        id: 'kobold_king',
        name: 'Kobold King',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.25, spd: 0.25, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '👑',
        skills: ['bash', 'frenzy'],
    },
    drake_hatchling: {
        id: 'drake_hatchling',
        name: 'Drake Hatchling',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.40, def: 0.25, spd: 0.30, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🦎',
        skills: [],
    },
    fire_drake: {
        id: 'fire_drake',
        name: 'Fire Drake',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.25, spd: 0.15, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🐉',
        skills: ['fireball'],
    },
    frost_drake: {
        id: 'frost_drake',
        name: 'Frost Drake',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.30, spd: 0.15, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🐉',
        skills: [],
    },
    shadow_drake: {
        id: 'shadow_drake',
        name: 'Shadow Drake',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.20, spd: 0.25, will: 0.10 },
        archetype: Archetype.ASSASSIN,
        icon: '🐉',
        skills: ['backstab'],
    },
    storm_drake: {
        id: 'storm_drake',
        name: 'Storm Drake',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.25, spd: 0.20, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🐉',
        skills: ['spark', 'cleave'],
    },
    wyvern_hatchling: {
        id: 'wyvern_hatchling',
        name: 'Wyvern Hatchling',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.20, spd: 0.30, will: 0.05 },
        archetype: Archetype.ASSASSIN,
        icon: '🐉',
        skills: [],
    },
    wyvern: {
        id: 'wyvern',
        name: 'Wyvern',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.50, def: 0.25, spd: 0.20, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐉',
        skills: ['cleave'],
    },
    wyvern_matriarch: {
        id: 'wyvern_matriarch',
        name: 'Wyvern Matriarch',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.50, def: 0.30, spd: 0.15, will: 0.05 },
        archetype: Archetype.BRUISER,
        icon: '🐉',
        skills: ['cleave', 'frenzy'],
    },
    pseudodragon: {
        id: 'pseudodragon',
        name: 'Pseudodragon',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.25, def: 0.15, spd: 0.35, will: 0.25 },
        archetype: Archetype.MAGE,
        icon: '🐉',
        skills: [],
    },
    dragon_wyrmling: {
        id: 'dragon_wyrmling',
        name: 'Dragon Wyrmling',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.25, spd: 0.20, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🐲',
        skills: ['fireball'],
    },
    young_dragon: {
        id: 'young_dragon',
        name: 'Young Dragon',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.30, spd: 0.15, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🐲',
        skills: ['fireball', 'cleave'],
    },
    adult_dragon: {
        id: 'adult_dragon',
        name: 'Adult Dragon',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.30, spd: 0.10, will: 0.20 },
        archetype: Archetype.PALADIN,
        icon: '🐲',
        skills: ['fireball', 'cleave', 'frenzy'],
    },
    ancient_dragon: {
        id: 'ancient_dragon',
        name: 'Ancient Dragon',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.30, spd: 0.10, will: 0.25 },
        archetype: Archetype.PALADIN,
        icon: '🐲',
        skills: ['meteor', 'cleave', 'frenzy', 'mana_shield'],
    },
    dragon_lord: {
        id: 'dragon_lord',
        name: 'Dragon Lord',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.30, spd: 0.10, will: 0.25 },
        archetype: Archetype.PALADIN,
        icon: '🐲',
        skills: ['meteor', 'cleave', 'frenzy', 'mana_shield', 'second_wind'],
    },
    red_dragon: {
        id: 'red_dragon',
        name: 'Red Dragon',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.25, spd: 0.10, will: 0.25 },
        archetype: Archetype.BRUISER,
        icon: '🐲',
        skills: ['fireball', 'cleave', 'frenzy'],
    },
    blue_dragon: {
        id: 'blue_dragon',
        name: 'Blue Dragon',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.35, def: 0.25, spd: 0.15, will: 0.25 },
        archetype: Archetype.PALADIN,
        icon: '🐲',
        skills: ['spark', 'cleave', 'mana_shield'],
    },
    green_dragon: {
        id: 'green_dragon',
        name: 'Green Dragon',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.25, spd: 0.20, will: 0.25 },
        archetype: Archetype.MAGE,
        icon: '🐲',
        skills: ['soul_rend', 'mana_shield'],
    },
    black_dragon: {
        id: 'black_dragon',
        name: 'Black Dragon',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.25, spd: 0.15, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🐲',
        skills: ['cleave', 'frenzy', 'leech'],
    },
    white_dragon: {
        id: 'white_dragon',
        name: 'White Dragon',
        family: EnemyFamily.DRACONIC,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.30, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🐲',
        skills: ['cleave', 'bash', 'frenzy'],
    },

    // ==================== ABOMINATION (26) ====================
    // Slimes, mimics, beholders, mind flayers — unnatural horrors

    gray_ooze: {
        id: 'gray_ooze',
        name: 'Gray Ooze',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.30, def: 0.45, spd: 0.05, will: 0.20 },
        archetype: Archetype.TANK,
        icon: '🫧',
        skills: [],
    },
    green_slime: {
        id: 'green_slime',
        name: 'Green Slime',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.NO_REPLETE,
        statDist: { atk: 0.35, def: 0.40, spd: 0.05, will: 0.20 },
        archetype: Archetype.TANK,
        icon: '🟢',
        skills: [],
    },
    gelatinous_cube: {
        id: 'gelatinous_cube',
        name: 'Gelatinous Cube',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.45, spd: 0.05, will: 0.15 },
        archetype: Archetype.TANK,
        icon: '🧊',
        skills: [],
    },
    black_pudding: {
        id: 'black_pudding',
        name: 'Black Pudding',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.40, spd: 0.05, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '⬛',
        skills: [],
    },
    ochre_jelly: {
        id: 'ochre_jelly',
        name: 'Ochre Jelly',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.40, spd: 0.05, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🟠',
        skills: [],
    },
    elder_ooze: {
        id: 'elder_ooze',
        name: 'Elder Ooze',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.45, spd: 0.05, will: 0.10 },
        archetype: Archetype.TANK,
        icon: '🫧',
        skills: ['leech'],
    },
    mimic_small: {
        id: 'mimic_small',
        name: 'Small Mimic',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.30, spd: 0.20, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '📦',
        skills: ['backstab'],
    },
    mimic: {
        id: 'mimic',
        name: 'Mimic',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.30, spd: 0.15, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '📦',
        skills: ['backstab'],
    },
    greater_mimic: {
        id: 'greater_mimic',
        name: 'Greater Mimic',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.35, spd: 0.10, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '🏠',
        skills: ['backstab', 'bash'],
    },
    house_mimic: {
        id: 'house_mimic',
        name: 'House Mimic',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.40, spd: 0.05, will: 0.15 },
        archetype: Archetype.TANK,
        icon: '🏠',
        skills: ['bash', 'cleave'],
    },
    gazer: {
        id: 'gazer',
        name: 'Gazer',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.20, def: 0.15, spd: 0.30, will: 0.35 },
        archetype: Archetype.MAGE,
        icon: '👁️',
        skills: ['spark'],
    },
    spectator: {
        id: 'spectator',
        name: 'Spectator',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.25, def: 0.20, spd: 0.25, will: 0.30 },
        archetype: Archetype.MAGE,
        icon: '👁️',
        skills: ['spark', 'mana_shield'],
    },
    beholder_zombie: {
        id: 'beholder_zombie',
        name: 'Beholder Zombie',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.30, def: 0.35, spd: 0.10, will: 0.25 },
        archetype: Archetype.BRUISER,
        icon: '👁️',
        skills: ['soul_rend'],
    },
    beholder: {
        id: 'beholder',
        name: 'Beholder',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.20, def: 0.20, spd: 0.20, will: 0.40 },
        archetype: Archetype.MAGE,
        icon: '👁️',
        skills: ['fireball', 'spark', 'soul_rend'],
    },
    death_tyrant: {
        id: 'death_tyrant',
        name: 'Death Tyrant',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.20, def: 0.25, spd: 0.15, will: 0.40 },
        archetype: Archetype.MAGE,
        icon: '👁️',
        skills: ['meteor', 'soul_rend', 'mana_shield'],
    },
    mind_flayer_thrall: {
        id: 'mind_flayer_thrall',
        name: 'Mind Flayer Thrall',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.30, spd: 0.15, will: 0.15 },
        archetype: Archetype.BRUISER,
        icon: '🧟',
        skills: [],
    },
    mind_flayer: {
        id: 'mind_flayer',
        name: 'Mind Flayer',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.20, def: 0.20, spd: 0.20, will: 0.40 },
        archetype: Archetype.MAGE,
        icon: '🐙',
        skills: ['soul_rend', 'leech'],
    },
    ulitharid: {
        id: 'ulitharid',
        name: 'Ulitharid',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.20, def: 0.25, spd: 0.15, will: 0.40 },
        archetype: Archetype.MAGE,
        icon: '🐙',
        skills: ['soul_rend', 'leech', 'mana_shield'],
    },
    elder_brain: {
        id: 'elder_brain',
        name: 'Elder Brain',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.10, def: 0.30, spd: 0.05, will: 0.55 },
        archetype: Archetype.SUMMONER,
        icon: '🧠',
        skills: ['soul_rend', 'summon', 'mana_shield'],
    },
    aboleth_spawn: {
        id: 'aboleth_spawn',
        name: 'Aboleth Spawn',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.35, def: 0.30, spd: 0.15, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '🐙',
        skills: [],
    },
    aboleth: {
        id: 'aboleth',
        name: 'Aboleth',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.30, spd: 0.10, will: 0.30 },
        archetype: Archetype.PALADIN,
        icon: '🐙',
        skills: ['soul_rend', 'leech', 'mana_shield'],
    },
    gibbering_mouther: {
        id: 'gibbering_mouther',
        name: 'Gibbering Mouther',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.40, def: 0.30, spd: 0.10, will: 0.20 },
        archetype: Archetype.BRUISER,
        icon: '👄',
        skills: [],
    },
    otyugh: {
        id: 'otyugh',
        name: 'Otyugh',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.STANDARD,
        statDist: { atk: 0.45, def: 0.35, spd: 0.10, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash'],
    },
    neo_otyugh: {
        id: 'neo_otyugh',
        name: 'Neo-Otyugh',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.45, def: 0.40, spd: 0.05, will: 0.10 },
        archetype: Archetype.BRUISER,
        icon: '👹',
        skills: ['bash', 'cleave'],
    },
    shoggoth: {
        id: 'shoggoth',
        name: 'Shoggoth',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.40, def: 0.40, spd: 0.05, will: 0.15 },
        archetype: Archetype.TANK,
        icon: '🫧',
        skills: ['bash', 'cleave', 'second_wind'],
    },
    eldritch_horror: {
        id: 'eldritch_horror',
        name: 'Eldritch Horror',
        family: EnemyFamily.ABOMINATION,
        hunger: HungerAccess.FULL_ACCESS,
        statDist: { atk: 0.30, def: 0.25, spd: 0.10, will: 0.35 },
        archetype: Archetype.PALADIN,
        icon: '👁️',
        skills: ['meteor', 'soul_rend', 'mana_shield', 'second_wind'],
    },
};

Object.freeze(BESTIARY);

// Export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        EnemyFamily,
        HungerAccess,
        Archetype,
        BESTIARY,
    };
}
